services:
  postgres:
    image: postgres:13.3
    container_name: postgres_container
    environment:
      POSTGRES_USER: adrian
      POSTGRES_PASSWORD: nairda
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=adrian@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=nairda
    ports:
      - "5050:80"